# Generated by Django 3.1.7 on 2021-09-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type1', models.CharField(blank=True, max_length=100, null=True)),
                ('type2', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('hp', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('sp_atk', models.IntegerField(blank=True, null=True)),
                ('sp_def', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('legendary', models.BooleanField(default=False)),
            ],
        ),
    ]
